// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/oo/SingletonDemo.java

package oo;

public class SingletonDemo {
    public static void main(String[] args) {

        // tag::enumBased[]
        // Demonstrate the enum method:
        EnumSingleton.INSTANCE.demoMethod();
        // end::enumBased[]

        // tag::codeBased[]
        // Demonstrate the codeBased method:
        Singleton.instance().demoMethod();
        // end::codeBased[]
    }
}
