// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/multireleasejar/versions/16/Data.java

package mrjdemo;

// tag::main[]
public record Data() {
  public String type() {
    return "record";
  }
}
// end::main[]
