// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/datetime/CurrentDateTime.java

package datetime;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Tutorial/Example of LocalDate
 */
// tag::main[]
public class CurrentDateTime {
  public static void main(String[] args) {
    LocalDate dNow = LocalDate.now();
    System.out.println(dNow);
    LocalTime tNow = LocalTime.now();
    System.out.println(tNow);
    LocalDateTime now = LocalDateTime.now();
    System.out.println(now);
  }
}
// end::main[]
