// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/threads/ScopedValueDemo1.java

// tag::main[]
static final ScopedValue<Client> CLIENT = ScopedValue.newInstance();

private final Client currentClient = new Client(1234);

void main() {
  ScopedValue.runWhere(CLIENT, currentClient, () -> doSomething());
}

void doSomething() {
  doSomethingElse();
}
void doSomethingElse() {
  doYetMore();
}
void doYetMore() {
  Client client = CLIENT.get();
  System.out.println("In doYetMore, client = " + client);
}

record Client(int id) { }
// end::main[]
