// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/numbers/FormatPlurals.java

package numbers;

/**
 * Format a plural correctly, by hand.
 * @author Ian F. Darwin, https://darwinsys.com/
 */
// tag::main[]
public class FormatPlurals {
  public static void main(String[] argv) {
    report(0);
    report(1);
    report(2);
  }

  /** report -- using conditional operator */
  public static void report(int n) {
    System.out.println("We used " + n + " item" + (n==1?"":"s"));
  }
}
// end::main[]
