// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/numbers/StringToDouble.java

package numbers;


public class StringToDouble {

  // tag::main[]
  public static void main(String[] argv) {
    String aNumber = argv[0];  // not argv[1]
    double result;
    try {
      result = Double.parseDouble(aNumber); 
      System.out.println("Number is " + result);
    } catch(NumberFormatException exc) {
      System.out.println("Invalid number " + aNumber);
      return;
    }
  }
  // end::main[]
}
