// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/multireleasejar/Data.java

package mrjdemo;

// tag::main[]
public class Data {
  String type() {
    return "class";
  }
}
// end::main[]
