// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/multireleasejar/Main.java

package mrjdemo;

// tag::main[]
public class Main {
  public static void main(String[] args) { 
    var type = new Data().type();
    System.out.printf("Run with a Data object of type '%s'.\n", type);
  }
}
// end::main[]
