// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/io/ReadCharsOneAtATime.java

package io;

import java.io.IOException;
import java.io.Reader;

/** This works, but is likely to be very slow. */
// tag::main[]
public class ReadCharsOneAtATime {

    void doFile(Reader is) throws IOException {
        int c;
        while ((c=is.read( )) != -1) {
            System.out.print((char)c);
        }
    }
}
// end::main[]
