// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/logging/JulLogDemo.java

package logging;

// tag::main[]
import java.util.logging.Logger;

public class JulLogDemo {
  public static void main(String[] args) {

    Logger myLogger = Logger.getLogger("com.darwinsys");

    Object o = new Object();
    myLogger.info("I created an object: " + o);
  }
}
// end::main[]
