// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/logging/Log4JDemo.java

package logging;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

// tag::main[]
public class Log4JDemo {

  private static Logger myLogger = LogManager.getLogger();

  public static void main(String[] args) {

    Object o = new Object();
    myLogger.info("I created an object: " + o);

  }
}
// end::main[]
