// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/di0/SpringBeanConfig.java

package di0;

import jakarta.enterprise.inject.Produces;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

// tag::main[]
@Configuration
public class SpringBeanConfig {
    @Bean
    public Processor processor() {
        return new Process();
    }
}
// end::main[]
