// DO NOT EDIT this file; make changes in Git repo e.g.,
// javasrc/main/src/main/java/reflection/cooklet/DemoCooklet.java

package reflection.cooklet;

// tag::main[]
public class DemoCooklet extends Cooklet {
  public void work() {
    System.out.println("I am busy baking cookies.");
  }
  public void terminate() {
    System.out.println("I am shutting down my ovens now.");
  }
}
// end::main[]
